layout_spectrum: 1
color:
  saturation: 0.9838518
  lightness: 0.2267145
  brandStrength: 1
  brandColors:
    - '#5B4239'
    - '#FFFFFF'
    - '#F35236'
    - '#02D080'
    - '#FBEB01'
  rhythmicContrast: 0.623946
typography_spectrum: 0.1070826
name: Flockmen
